################################################

# compile

################################################

all:
	make all -C process1
	make all -C process2

clean:
	make clean -C process1
	make clean -C process2

.PHONY: all clean

